version: '3'
networks:
    cache: {}
services:
    proxy:
        build:
            context: '.'
            dockerfile: 'Dockerfile.proxy'
        restart: unless-stopped
        networks:
            cache: {}
    varnish:
        build:
            context: '.'
            dockerfile: 'Dockerfile.varnish'
        restart: unless-stopped
        networks:
            cache: {}
        ports:
            - '51442:80'
